In [1]:
import numpy as np

### Zadania

1. Utworzyć tablicę zawierającą 50 piątek.
2. Utworzyć tablicę o rozmiarach 5x5 z wartościami od 1 do 25.
3. Utworzyć tablicę tablicę liczb parzystych od 10 do 50.
4. Utworzyć macierz, w której na przekątnej znajdą się wartości równe 8, a pozostałe będą wynosiły 0.
5. Utworzyć tablicę o rozmiarach 10x10 z wartościami zwiększającymi się o 0.01.
6. Utworzyć przestrzeń liniową 50 wartości z zakresu 0-1.
7. Wybrać podtablicę 12-elementową, z tablicy utworzonej w zadaniu 2, z wartościami w zakresie 12-25.
8. Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę.
9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2.
10. Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów.
11. Przygotować macierz, która w każdym wierszu będzie zawierała wartości od 1 do 5. Uwaga, nie używać w tym celu gotowych list do utworzenia macierzy.
12. Utworzyć wektor 10-elementowy składający się z wartości losowych, a następnie wstawić 0 w miejsce wartości najmniejszej.
13. Napisać skrypt, który w losowym wektorze Z znajdzie najbliższą wartość losowego skalara v.
14. Wygenerować losową macierz M o rozmiarach 5x8, a następnie zamienić kolejnością 2 losowo wskazane wiersze.
15. Wygenerować macierz o rozmiarach 5x5 wypełnioną dowolnymi kolejnymi wartościami, a następnie przetransformować macierz do postaci wektora kolumnowego zachowując wszystkie wartości.

In [2]:
### Ad. 1
arr = np.full(50, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [3]:
### Ad. 2
arr2 = np.array(range(1, 26))
arr2 = arr2.reshape(5, 5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
### Ad. 3
arr3 = np.array(range(10, 51, 2))
print(arr3)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [5]:
### Ad. 4
arr4 = np.zeros((5, 5))
np.fill_diagonal(arr4, 8)
print(arr4)

[[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]]


In [6]:
### Ad. 5
arr5 = np.arange(0.01, 1.01, 0.01)
arr5 = arr5.reshape(10, 10)
print(arr5)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [7]:
### Ad. 6
arr6 = np.linspace(0, 1, 50)
print(arr6)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [8]:
### Ad. 7
arr7 = arr2[2:7, 1:5]
print(arr7)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [9]:
### Ad. 8
arr8 = arr2[0:3, 1]
arr8 = arr8.reshape(3, 1)
print(arr8)

[[ 2]
 [ 7]
 [12]]


In [19]:
### Ad. 9
arr9 = arr2[-2:, :]
# arr9 = arr9.sum(axis=1)
print(arr9.sum(), arr9.sum(axis=1))

205 [ 90 115]


In [152]:
### Ad. 10
num_dimensions = np.random.randint(1, 4)
shape = tuple(np.random.randint(1, 11, size=num_dimensions))
tensor = np.random.randint(
    10,
    size=shape
  )
print(tensor)

[2 4 6 5 7]


In [12]:
### Ad. 11
matrix11 = np.zeros((10, 5))
matrix11 += np.arange(1, 6)
print(matrix11)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [13]:
### Ad. 12
vector12 = np.random.randint(10, size=10)
min_val = vector12.min()
vector12[vector12 == min_val] = 0
print(vector12, vector12[vector12 == min_val], min_val)

[0 5 8 3 9 3 0 5 0 3] [] 1


In [14]:
### Ad. 13
arr13 = np.random.randint(10, size=10)
v = np.random.randint(10)
print(arr13, v)

[7 2 4 3 5 2 5 9 2 3] 6


In [15]:
### Ad. 14
matrix14 = np.random.randint(10, size=(5, 8))
print(matrix14)

[[5 3 5 5 3 2 6 0]
 [3 8 1 8 6 4 3 3]
 [0 5 9 4 3 9 7 1]
 [6 2 9 4 1 7 5 6]
 [3 1 5 6 7 4 7 2]]


In [16]:
randomRows = np.random.randint(0, matrix14.shape[0], 2)
matrix14[[randomRows[0], randomRows[1]]] = matrix14[[randomRows[1], randomRows[0]]]
matrix14[[randomRows[1], randomRows[0]]] = matrix14[[randomRows[0], randomRows[1]]]
print(matrix14)

[[5 3 5 5 3 2 6 0]
 [3 8 1 8 6 4 3 3]
 [0 5 9 4 3 9 7 1]
 [6 2 9 4 1 7 5 6]
 [3 1 5 6 7 4 7 2]]


In [17]:
### Ad. 15
matrix15 = np.random.randint(10, size=(5, 5))
matrix15 = matrix15.reshape(-1, 1)
print(matrix15)

[[2]
 [8]
 [3]
 [0]
 [8]
 [8]
 [4]
 [6]
 [4]
 [3]
 [6]
 [9]
 [2]
 [4]
 [1]
 [2]
 [9]
 [6]
 [5]
 [4]
 [3]
 [9]
 [4]
 [4]
 [9]]
